### ISSUE TITLE
allow modification of argument processor list

### ISSUE THREAD

**Issue by smoi23** [TrixterFilm/jobtronaut#35]
## Goal
Implement functionality to inherit, override and extend argument processors at `TaskWithOverrides`.

## Motivation
'TaskWithOverrides' allows customization of existing tasks and override different parameters like 'argument_processors'. The 'argument_processors' argument accepts a list of 'ProcessDefinitions' which replaces the original entirely.
To not only replace all processors but rather modify existing list we can define operations similar to list operations - 'remove, replace, prepend, append' and apply them accordingly. This way we can finer control overrides.

#### Example Usage
```python
TaskWithOverrides(
    "FooBarTask",
    argument_processors=TaskWithOverrides.ArgumentProcessorOverrides(
        {
            "prepend": [ProcessorDefinition1, ProcessorDefinition2],  # accepts list/tuple of ProcessorDefinitions or single ProcessorDefinition
            "replace": {0: ProcessorDefinition3, 2: ProcessorDefinition4},  # requires mapping of {index: ProcessorDefinition}
            "remove": [1, 3],  #accepts list/tuple of indices or single index as int
            "append": [ProcessorDefinition5, ProcessorDefinition6]  # accepts list/tuple of ProcessorDefinitions or single ProcessorDefinition
        }
    )
)

```

Define object ('ArgumentProcessorOverrides') which holds processor definitions per operation and use this instead of a list. e.g. `argument_processor = ArgumentProcessorOverrides(..)`. 

Extend `TaskWithOverrides.get` in order to decide if a list or 'ArgumentProcessorOverrides' object was provided and modify the overrides by implementing the operations 'remove, replace, prepend, append'. In case of 'remove' and 'replace' the operation are based on the index of the original defined processor list.

**Comment by rkoschmitzky** [comment]
This was released.
